### ISSUE TITLE
Theme instructions.

### ISSUE THREAD

**Issue by mlee12382** [moggieuk/KlipperScreen-Happy-Hare-Edition#10]
### Requested feature

Can we get instructions specifically for what we need to change or add to other themes to make the HH icons show up properly?

**Comment by moggieuk** [comment]
Can you provide more information - what are you trying to do?   the HH functionality works with all the default 4 themes?  Are you creating a new one from scratch?

**Comment by mlee12382** [comment]
Yes HH works with the 4 default themes. I have themes that I've downloaded from VzBot github and from TeamFDM that I like using and while the functions for HH work with them, ie I can access all the menus and screens, none of the icons are visible they're just blank. I've looked through the files but nothing jumps out as being the section that needs to be modified to make it visible.

**Comment by mlee12382** [comment]
Yes, they all get added to the themes folder like the default 4.

**Comment by moggieuk** [comment]
Actually I check the installer and it should link all Happy Hare icons into every theme directory already.  Are you sure you ran:
```
cd ~/KlipperScreen
happy_hare/install_ks.sh -g <num_gates...>
```

**Comment by moggieuk** [comment]
It will update the mmu_KlipperScreen.conf file, that's all. The old one is backed up in the same directory.  Your main KlipperScreen.conf file should have this include in it

```
# 
# MMU "Happy Hare edition" menus
#
[include mmu_klipperscreen.conf]

[printer BigRed]
moonraker_host: 192.168.0.103

```

then nothing is replaced (unless you customized my default Happy Hare menus)

**Comment by mlee12382** [comment]
> It will update the mmu_KlipperScreen.conf file, that's all. The old one is backed up in the same directory.  Your main KlipperScreen.conf file should have this include in it
> 
> ```
> # 
> # MMU "Happy Hare edition" menus
> #
> [include mmu_klipperscreen.conf]
> 
> [printer BigRed]
> moonraker_host: 192.168.0.103
> 
> ```
> 
> then nothing is replaced (unless you customized my default Happy Hare menus)
> 

I've got that included and the menus are accessible on the custom themes but there's no icons visible where they should be. I'll look again when I get home but I don't remember seeing any mmu*.svg files in the default theme folders. Maybe I just missed them.

**Comment by mlee12382** [comment]
> It will update the mmu_KlipperScreen.conf file, that's all. The old one is backed up in the same directory.  Your main KlipperScreen.conf file should have this include in it
> 
> ```
> # 
> # MMU "Happy Hare edition" menus
> #
> [include mmu_klipperscreen.conf]
> 
> [printer BigRed]
> moonraker_host: 192.168.0.103
> 
> ```
> 
> then nothing is replaced (unless you customized my default Happy Hare menus)
> 
> Without running ./install_ks.sh again there is lots that might not work.
> 

So I had missed the svg files because they were symlinks but I was able to copy them to the other  theme folders and now everything is showing up properly ![20231208_182950.jpg](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/89716126/bcfe253a-58f8-443f-bf74-2b6c845dfe36)

Thanks for the help.
