### ISSUE TITLE
[BUG] MoonRaker warning after installing KlipperScreen-Happy-Hare-Edition

### ISSUE THREAD

**Issue by mikeytdisco** [moggieuk/KlipperScreen-Happy-Hare-Edition#11]
### What happened?

2023-11-28 15:30:48,290 [server.py:add_warning()] - [update_manager KlipperScreen-happy_hare]: Option 'managed_services: KlipperScreen' contains an invalid value 'KlipperScreen'.  All values must be one of the following choices: ['KlipperScreen-happy_hare', 'klipper', 'moonraker']
[moonraker (1).log](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/files/13494486/moonraker.1.log)

### What did you expect to happen instead?

No warning message.

### How to reproduce this bug?

This message on startup
![MoonRakerWarning](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/17346646/5831fee8-2c0d-4c7f-a37c-52bf739e0e24)
[logs-20231128-154305.zip](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/files/13494520/logs-20231128-154305.zip)

### Log output

```shell
KlipperScreen.log is in the logs-20231128-154305.zip file uploaded above.
```

**Comment by devildog125** [comment]
I'm getting the same message
