### ISSUE TITLE
[FR] icôn printers Select 

### ISSUE THREAD

**Issue by mickael13160** [moggieuk/KlipperScreen-Happy-Hare-Edition#19]
### Requested feature

When multiple printers are configured, their icons can be customized

**Comment by moggieuk** [comment]
This is a good idea but you should submit an issue to the upstream project here: https://github.com/KlipperScreen/KlipperScreen

This is a fork of the original that stays up-to-date and adds functionality to support Happy Hare MMU.

**Comment by mickael13160** [comment]
hello so since the last update this is possible I have the logo of my 3d printer in the choice thank you for the update

**Comment by moggieuk** [comment]
At, ok. So if a feature on the upstream klipperscreen it should be possible here too. 

I haven’t used the feature but have you tried with KS-HH edition?
