### ISSUE TITLE
[BUG] Spoolman Option inside HH menu make display width change and go off screen in all menus

### ISSUE THREAD

**Issue by jackjohnsonuk** [moggieuk/KlipperScreen-Happy-Hare-Edition#21]
### What happened?

If I go into the HH>More>Spoolman menu option the screen display parameters change throwing off all the menus, until I restart KS.

I have made a video to show the issue to, linked below:
https://photos.app.goo.gl/hnxSrcjn2XcN675AA

### What did you expect to happen instead?

The display to stay confined to the parameters of the screen

### How to reproduce this bug?

Open the spoolman menu inside HH

### Log output

[KlipperScreen.log](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/files/15360870/KlipperScreen.log)

**Comment by moggieuk** [comment]
Is this still happening since my update today (I caught up with all upstream changes)?   Unfortunately you video doesn't show the spoolman screen.  Can you update:
```
cd KlipperScreen
./install_ks.sh -g 4
```
Then help with picture of the screen with problems..

**Comment by jackjohnsonuk** [comment]
Hi Moggie,

Unfortunately I'm still getting the same issue.

Picture attached of the spoolman screen, which you can't see much of as most of it is off the screen. This screen resolution bug seems to be persistent with the only way to restore the resolution to restart klipper screen.

Any suggestions would be welcome.

Thanks 

J

![PXL_20240525_204533883.jpg](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/32000001/15825e28-9499-42f5-a42d-fbb45f44a1c0)

![PXL_20240525_204537426.MP.jpg](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/32000001/81a7a3cd-4efb-4f5f-bcd2-75bf10516321)

![PXL_20240525_204541971.jpg](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/32000001/0bea650e-3493-4a4b-8088-4e433f8bc320)

**Comment by moggieuk** [comment]
Thanks. The screenshot is helpful.  I may be because I'm not truncating the "PLA- Silk" and it is a couple of characters too long...

**Comment by moggieuk** [comment]
Ok.  If you update to the latest I addressed the issue. Unfortunately there is a lot of info to display so the material field is restricted to the first 6 characters.   "PLA - Slik" will thus display as "PLA - ".   Maybe renaming to "PLA-Silk" would at least display as "PLA-Si"

**Comment by jackjohnsonuk** [comment]
Brilliant, working great! Thank you :)

**Comment by jackjohnsonuk** [comment]
Brilliant, it's working fine now!  Thank you for your help with this
