### ISSUE TITLE
Problem screen size and page print not available 

### ISSUE THREAD

**Issue by Thomsen1982** [moggieuk/KlipperScreen-Happy-Hare-Edition#24]
### What happened?

1. after a Klipper screen update, I don't know which one, the Print page was no longer accessible. I therefore have no access to the print jobs via the display. The screenshot shows the error message.

2. the displayed page size is too large after an update and no longer fits on the display. In the screenshot you can see that either a scrollbar is added or something is cut off.

### What did you expect to happen instead?

1. the page print is available and I can start one of the print jobs
2. the page size match the display size as before

### How to reproduce this bug?

1. press on button print 
2. Start the printer, the pages always to large

### Additional information:

Display is a BIGTREETECH PI TFT50 V2.0 
Klipper Screen happy hare edition is the latest version

screenshots
![IMG_1083](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/123178255/7844552c-a91a-4abf-b77f-825352944d87)
![IMG_1082](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/123178255/e28ed222-b69a-4a3a-9eea-1262da16c2cf)
![IMG_1081](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/123178255/7a5affc5-5d8f-426b-8b6c-aa63b082f679)

### Log output

[KlipperScreen.log](https://github.com/user-attachments/files/16043462/KlipperScreen.log)

**Comment by fabiandj64** [comment]
I got almost the same problems. Pages/symbols are too large and in the print page it only shows the filament assigned in the slicer and a giant "Print" Button but nothing else

**Comment by Thomsen1982** [comment]
I was able to solve the problem with the missing print page. See screenshot. Print.py was removed from the marked commit, for whatever reason. I have taken the file from the previous version and it works again. The print page is displayed again.

The problem with the symbols being too large still exists. Does anyone know in which file this information can be found, then I would also go to an older version.

![Bild 01 07 24 um 14 51](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/123178255/20c4f325-b51f-469a-965c-ca5658e3013a)

**Comment by fabiandj64** [comment]
My Print page looks like this. It shows the different filaments and just a big print button 
![20240709_191732](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/124401184/93792c4a-8728-4bc6-a4f0-cb63d9a7320f)

**Comment by moggieuk** [comment]
Sorry for the delay.  On initial glance this appears to be a bug in the upstream KlipperScreen -- I resync with upstream about every two week.  I'll do that again today, but can you tell me if this is still a problem?

**Comment by Thomsen1982** [comment]
No Problem,

with the Print Page, it is working after my fix. I also did an Update and it was already ok.

with the too large Pages, sometimes it match, sometimes it is too large. Really funny. I dont no what could be the problem. 
on the pi config i set the fix size of the Display, but it doesn t matter

**Comment by moggieuk** [comment]
I'm double checking that the upstream merge went ok.  Have just refreshed from upstream, but I think the problem is still there...!

**Comment by moggieuk** [comment]
Found the problem.  Definitely in KlipperScreen's new `gocdes.py` panel. Will try to fix.

**Comment by moggieuk** [comment]
Fix checked it.  Until "upstream" KlipperScreen fixes, I simply omit displaying the list of filament names...

**Comment by Thomsen1982** [comment]
Ok thanks
I Check it es soon as possible

**Comment by moggieuk** [comment]
Let me know.  It it likely that very long filename or slicers with more than about 12 extruders will still have issues. This panel needs a bit of love. I'm sure it will improve because it's quite new.

**Comment by fabiandj64** [comment]
The fix worked for me. Print Page now looks like this. Good job. Thanks :) 
![20240718_112418](https://github.com/user-attachments/assets/f7081522-bb40-4b0f-8d98-e1b3034ed930)

**Comment by moggieuk** [comment]
Cool. I submitted a bug report upstream. That particular confirmation panel needs a bit of love.  The author isn't anticipating long lists for filament.

**Comment by Thomsen1982** [comment]
Yes it looks good. Thanks

Only one item left to the main screen. See the third picture I added. Is it possible to reduce the icons on the right side? The scrollbar there is not needed and only available because of a little bit to big icons.

**Comment by fabiandj64** [comment]
I only have 5 icons there. Homing is under the "Move" tab for me. And I believe I don't have "Actions" and "Configuration"

**Comment by moggieuk** [comment]
@Thomsen1982  You seem to have a different button layout -- maybe you defined some extra buttons in your config?.   But anyway, if there is a layout problem you will have to go upstream to the original project -- I can't keep addressing bugs in the base KlipperScreen because of time but also it becomes a merge nightmare.  Whilst I try, I have to focus on the Happy Hare extensions..

**Comment by Thomsen1982** [comment]
Yes your right. Then I ask klipperscreen directly.

thanks for the fixes.
So I close the issue.

**Comment by Thomsen1982** [comment]
Problem is solved
