### ISSUE TITLE
[BUG] Predefined color selection list cannot be scrolled through.

### ISSUE THREAD

**Issue by kolbenhans** [moggieuk/KlipperScreen-Happy-Hare-Edition#3]
**Describe the bug**
Predefined color selection list cannot be scrolled through.

**To Reproduce**
1. Try to set the Filament Color in ERCF menu
2. Opening the drop-down list with predefined color names
3. The drop down is closing when you scroll down the list.

**Expected behavior**
Scroll through the full list, select one of the predefined colors

**Logfile**
Nothing can be found in the log file, as no error is triggered either.

**Comment by moggieuk** [comment]
Hmm, works for me (and the problem wouldn't be with my additions).  I wonder if you are scrolling the way the widget expects?  When it opens up to full window height you put your finger in the middle of the list and drag it up to scroll down.  I noticed that if you click at the bottom of the list it does close -- that seems to be Gtk behavior...

**Comment by kolbenhans** [comment]
i made a short example video of the issue
https://youtu.be/s_qIJJ0ILVg

**Comment by moggieuk** [comment]
The video was very helpful.  Are you sure you are making deliberate scrolling movements - it looks like the light touch is being interpreted as a selection and hence the window closes with selection.  Also if you lightly touch outside of the scrolled area I believe it will interpret as "cancel" i.e. close window without selecting new option.

Also, there is nothing that I can do about the behavior of the scrolling window because that is a widget in Gtk that KlipperScreen uses.  I'm just the custom screen sitting on top of everything else.

**Comment by kolbenhans** [comment]
Hey, sorry for the late reply. Yes i can also do long scrolling movements with the same result. i did this only for the video to show that i don't touch the upper or bottom part of the window :)

as probably seen in the video, i can scroll up and down until the first entry hits the top of the dropdown window, as soon as this happens, the selection drop down is closing.

**Comment by moggieuk** [comment]
Thanks for the video, that is very clear.  This is definitely a problem with either the base KlipperScreen or more likely the Gtk support on your particular screen device.  Unfortunately there isn't anything I can do differently .. I just give the list widget a selection list and it does the rest...

On my screen a thick white boarder appears at the top and bottom of the screen as I scroll in each direction.  I wonder if there is a misconfiguration of your screen resolution that might cause this?

**Comment by kolbenhans** [comment]
Hey Paul, no worries, i can live with it.
btw. i already checked the resolution and also added my display specific values of:
```
hdmi_cvt=1024 600 60 3 0 0 0
hdmi_group=2
hdmi_mode=87
hdmi_drive=2
```
to the  /boot/config.txt

Thanks anyway.
