### ISSUE TITLE
filament page showing "unknown" status after changing tools

### ISSUE THREAD

**Issue by garyd9** [moggieuk/KlipperScreen-Happy-Hare-Edition#6]
### What happened?

HH2 klipper screen (specifically on the page where the filament types/colors can be edited):  I have filament loaded in T0 and T1.  I do a "check gates" and the above mentioned page notes both gates as "available."  I then run "T0" to load the first gate to the extruder.  Then I run "T1" to load the second gate into the extruder.  The above mentioned page in KS shows the status of T0 as "unknown" instead of "available."

### What did you expect to happen instead?

This is likely because of the different "S" and "B" states that HH2 uses.  KS should recognize both "S" and "B" as being available.

### How to reproduce this bug?

see "what happened" for steps to repeat.

### Additional information:

If I use that filament page to manually mark a buffered filament as available, it resets the status of the gate to "S"  (This is probably fine as it's a more conservative default.)

Thank you for the awesome addition to KS!

### Log output

```shell
sorry, but I didn't grab it.  Not sure it's needed for something this simple.
```

**Comment by moggieuk** [comment]
Bug fixed. Thanks you!
