### ISSUE TITLE
[FR] Spoolman support

### ISSUE THREAD

**Issue by BioCookieYT** [moggieuk/KlipperScreen-Happy-Hare-Edition#7]
### Requested feature

Hi,
I was wondering if it is possible to integrate [Spoolman](https://github.com/Donkie/Spoolman) spools into the [filament editor](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/blob/master/docs/MMU.md#filament-editor). It would allow easier filament management with Klipper MMU systems. 

![image](https://github.com/moggieuk/KlipperScreen-Happy-Hare-Edition/assets/63932294/b5dc361c-1b81-46c6-a771-e62a404c8984)

**Comment by moggieuk** [comment]
It's in the works.  Very soon now...
